### ISSUE TITLE
Tail not showing all logs in run pods

### ISSUE THREAD

**Issue by odinnordico** [vmware-tanzu/apps-cli-plugin#351]
### Please fill out the issue checklist below and provide ALL the requested information.

- [x] I reviewed open and closed Github issues that may be related to my problem.
- [x] I am reporting a bug that others will be able to reproduce.

### Describe the bug

After creating a workload (`tanzu apps wld create`) and then tailing it (`tanzu apps wld tail`) just after create command finishes, the output logs does not show all the pod log

### Expected behavior

Al the log record produced by the workload pods should be shown in the tail output

### Steps to Reproduce

- Create a workload: `tawc spring-petclinic --git-tag=tap-1.2 --git-repo=https://github.com/sample-accelerators/spring-petclinic --type web -y`
- Tail the output of the workload creation creation `tanzu apps wld tail spring-petclinic`
- Use k9s, `kubectl get pod --watch` or other mechanism to be aware when the *deployment* pod is created
- When the *deployment* pod is created, tail the logs with `kubectl`: `k logs spring-petclinic-00001-deployment-<some-id> -f`
- Compare the output of the logs

### Screenshots

kubectl logs

![image](https://user-images.githubusercontent.com/2386675/192066333-99c1821e-34dc-411b-9d86-a702a794c3ef.png)

tail logs

![image](https://user-images.githubusercontent.com/2386675/192066380-48665b1c-6e31-4713-a08d-eafc2fa27099.png)

### Version (Apps plugin version, Version of K8s running on cluster)
Put the output of the following commad
```sh
tanzu version && tanzu apps version
``` 

version: v0.25.0
buildDate: 2022-08-05
sha: 8db7108d
v0.9.0

### Environment where the bug was observed (cloud, OS, etc)

cluster GCP - TAP 1.3.0-build.24
client MacOs 12.6 (21G115)

### Additional context & Relevant Debug Output (Logs, etc)

tested as well with non web app

```yaml
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: smtp-gateway
  labels:
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/part-of: spring-smtp-gateway
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  source:
    git:
      ref:
        branch: main
      url: https://github.com/kdvolder/spring-smtp-gateway.git
    subPath: smtp-gateway
  params:
  - name: ports
    value:
    - port: 25
      containerPort: 1026
      name: smtp
```
