### ISSUE TITLE
Workload get supports shorthand `-e` for `--export`

### ISSUE THREAD

**Issue by heyjcollins** [vmware-tanzu/apps-cli-plugin#388]
### Description of problem

Flags likely to be used repeatedly are good candidates for single character shortcuts.
`--export` doesn't have a shortcut currently.

### Proposed solution

Support `-e` for `--export`.

```gherkin
Given my apps plugin is pointed to a cluster with a workload named foo
When I run "tanzu apps workload get foo -e"
Then I see the current "workload.yaml" returned rather than the standard "get" output
```

#### Command incantation
```
tanzu apps workload get foo -e
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
  name: foo
  namespace: default
spec:
  source:
    image: gcr.io/pivotal-knative/jc-apps:latest@sha256:2b0bb7ae0d403a98fac94d58ecdebf3272c336c9b7ba02a2f9cbb84604f2b833
```

#### Help output
```
ta get -h
Get details from a workload

Usage:
  tanzu apps workload get <name> [flags]

Examples:
  tanzu apps workload get my-workload

Flags:
  -e, --export           export workload in yaml format
  -h, --help             help for get
  -n, --namespace name   kubernetes namespace (defaulted from kube config)
  -o, --output string    output the Workload formatted. Supported formats: "json", "yaml", "yml"

Global Flags:
      --context name      name of the kubeconfig context to use (default is current-context defined by kubeconfig)
      --kubeconfig file   kubeconfig file (default is $HOME/.kube/config)
      --no-color          deactivate color, bold, and emoji output
  -v, --verbose int32     number for the log level verbosity (default 1)
```
