### ISSUE TITLE
Publish the Apps CLI plugin release as OCI artifact stored in ghcr

### ISSUE THREAD

**Issue by atmandhol** [vmware-tanzu/apps-cli-plugin#491]
### Description of problem

Tanzu CLI supports installing plugins from an OCI repository. We currently do not create a release a version of our `apps` CLI in a publicly accessible OCI repository.

### Proposed solution

In addition to the Github Releases, we should start shipping Apps CLI as OCI artifact that is stored on the public ghcr repository.

### Example

Github Action step to login to ghcr.io
```
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
```

Update the Makefile `publish` step to publish artifacts to ghcr.io.
```
        version="${{ steps.get-version.outputs.version }}"
        distribution_repo="ghcr.io/${{ github.repository }}/distribution"
        discovery_repo="ghcr.io/${{ github.repository }}/discovery"
        repo_tag="${repo}:${version}"
```

```
tanzu builder publish --input-artifact-dir ./artifacts --plugins "apps" --version "${version}" --type oci --oci-discovery-image "${discovery_repo}" --oci-distribution-image-repository "${distribution_repo}"
```
