### ISSUE TITLE
`apply` doesn't remove the `LSP` workload annotation when switching from `--local-source` to `--git*`

### ISSUE THREAD

**Issue by heyjcollins** [vmware-tanzu/apps-cli-plugin#546]
### Please fill out the issue checklist below and provide ALL the requested information.

- [x] I reviewed open and closed Github issues that may be related to my problem.
- [x] I am reporting a bug that others will be able to reproduce.

### Describe the bug
`apply` doesn't remove the `LSP` workload annotation when switching from `--local-source` to `--git*`

### Expected behavior
The LSP annotation should be removed from the workload object and should show up in the diff that's displayed to the end user for approval.

### Steps to Reproduce
1. create a workload (use workload.yaml provided at the end of this issue) 
   ```
   ta apply annotation-bug-wld -f workload.yaml --local-path ../application-accelerator-samples/tanzu-java-web-app --debug --yes --live-update --tail --update-strategy replace
   ❗ WARNING: Configuration file update strategy is changing. By default, provided configuration files will replace rather than merge existing configuration. The change will take place in the January 2024 TAP release (use "--update-strategy" to control strategy explicitly).

   The files and/or directories listed in the .tanzuignore file are being excluded from the uploaded source code.
   Publishing source in "../application-accelerator-samples/tanzu-java-web-app" to "local-source-proxy.tap-local-source-system.svc.cluster.local/source:dev-annotation-bug-wld"...
   26.81 kB / 26.81 kB [-----------------------------------------------------------------------------------------------------------------] 100.00% 36.60 kB p/s
   26.81 kB / 26.81 kB [-----------------------------------------------------------------------------------------------------------------] 100.00% 36.59 kB p/s
   📥 Published source

   🔎 Create workload:
      1 + |---
      2 + |apiVersion: carto.run/v1alpha1
      3 + |kind: Workload
      4 + |metadata:
      5 + |  annotations:
      6 + |    local-source-proxy.apps.tanzu.vmware.com: gcr.io/pivotal-knative/lsp:dev-annotation-bug-wld@sha256:a4728f3d972867003abccf19be54c34b1377850518ab692eff9bec7c16ec419a
      7 + |  labels:
      8 + |    app.kubernetes.io/part-of: tanzu-java-web-app
      9 + |    apps.tanzu.vmware.com/workload-type: web
     10 + |  name: annotation-bug-wld
     11 + |  namespace: dev
     12 + |spec:
     13 + |  params:
     14 + |  - name: annotations
     15 + |    value:
     16 + |      autoscaling.knative.dev/minScale: "1"
     17 + |  - name: debug
     18 + |    value: "true"
     19 + |  - name: live-update
     20 + |    value: "true"
     21 + |  source:
     22 + |    image: gcr.io/pivotal-knative/lsp:dev-annotation-bug-wld@sha256:a4728f3d972867003abccf19be54c34b1377850518ab692eff9bec7c16ec419a
   👍 Created workload "annotation-bug-wld"

   To see logs:   "tanzu apps workload tail annotation-bug-wld --timestamp --since 1h"
   To get status: "tanzu apps workload get annotation-bug-wld"
   ```
2. Note the presence of the `local-source-proxy.apps.tanzu.vmware.com` annotation
   ```
   ta get annotation-bug-wld --export
   ---
   apiVersion: carto.run/v1alpha1
   kind: Workload
   metadata:
     annotations:
       local-source-proxy.apps.tanzu.vmware.com: gcr.io/pivotal-knative/lsp:dev-annotation-bug-wld@sha256:a4728f3d972867003abccf19be54c34b1377850518ab692eff9bec7c16ec419a
     labels:
       app.kubernetes.io/part-of: tanzu-java-web-app
       apps.tanzu.vmware.com/workload-type: web
     name: annotation-bug-wld
     namespace: dev
   spec:
     params:
     - name: annotations
       value:
         autoscaling.knative.dev/minScale: "1"
     - name: debug
       value: "true"
     - name: live-update
       value: "true"
     source:
       image: gcr.io/pivotal-knative/lsp:dev-annotation-bug-wld@sha256:a4728f3d972867003abccf19be54c34b1377850518ab692eff9bec7c16ec419a
   ```
3. Update the workload to now use `--git*` source instead (remember that workload.yaml has git source)
   ```
   ta apply -f workload.yaml
   ❗ WARNING: Configuration file update strategy is changing. By default, provided configuration files will replace rather than merge existing configuration. The change will take place in the January 2024 TAP release (use "--update-strategy" to control strategy explicitly).

   🔎 Update workload:
   ...
   18, 18   |    value: "true"
   19, 19   |  - name: live-update
   20, 20   |    value: "true"
   21, 21   |  source:
   22     - |    image: gcr.io/pivotal-knative/lsp:dev-annotation-bug-wld@sha256:a4728f3d972867003abccf19be54c34b1377850518ab692eff9bec7c16ec419a
       22 + |    git:
       23 + |      ref:
       24 + |        branch: main
       25 + |      url: https://github.com/sample-accelerators/tanzu-java-web-app
   ❓ Really update the workload "annotation-bug-wld"? [yN]: y
   👍 Updated workload "annotation-bug-wld"

   To see logs:   "tanzu apps workload tail annotation-bug-wld --timestamp --since 1h"
   To get status: "tanzu apps workload get annotation-bug-wld"
   ```
  * **NOTE: ^^** diff doesn't include the removal of the `local-source-proxy.apps.tanzu.vmware.com` annotation
4. Review the on-cluster spec for the workload (notice it contains the annotation **AND** the git source which should be mutually exclusive)
   ```
   ta get annotation-bug-wld --export
   ---
   apiVersion: carto.run/v1alpha1
   kind: Workload
   metadata:
     annotations:
       local-source-proxy.apps.tanzu.vmware.com: gcr.io/pivotal-knative/lsp:dev-annotation-bug-wld@sha256:a4728f3d972867003abccf19be54c34b1377850518ab692eff9bec7c16ec419a
     labels:
       app.kubernetes.io/part-of: tanzu-java-web-app
       apps.tanzu.vmware.com/workload-type: web
     name: annotation-bug-wld
     namespace: dev
   spec:
     params:
     - name: annotations
       value:
         autoscaling.knative.dev/minScale: "1"
     - name: debug
       value: "true"
     - name: live-update
       value: "true"
     source:
       git:
         ref:
           branch: main
         url: https://github.com/sample-accelerators/tanzu-java-web-app
   ```

### Version (Apps plugin version, Version of K8s running on cluster)
Put the output of the following commad
```
tanzu version && tanzu apps version
version: v0.28.1
buildDate: 2023-03-07
sha: 0e6704777-dirty
v0.12.0-build.1-dev-f8f2fd47
``` 

### Environment where the bug was observed (cloud, OS, etc)
TAP 1.5 with LSP manually installed.

#### Workload.yaml
```
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: annotation-bug-wld
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tanzu-java-web-app
spec:
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/sample-accelerators/tanzu-java-web-app
      ref:
        branch: main
```
