### ISSUE TITLE
apply/create - `local-source-proxy.apps.tanzu.vmware.com` isn't being removed when included in workload.yaml AND `--source-image` flag/value is included

### ISSUE THREAD

**Issue by heyjcollins** [vmware-tanzu/apps-cli-plugin#562]
### Please fill out the issue checklist below and provide ALL the requested information.

- [x] I reviewed open and closed Github issues that may be related to my problem.
- [x] I am reporting a bug that others will be able to reproduce.

### Describe the bug
apply/create - `local-source-proxy.apps.tanzu.vmware.com` isn't being removed when included in workload.yaml AND `--source-image` flag/value is included

### Expected behavior
`local-source-proxy.apps.tanzu.vmware.com` should be removed

### Steps to Reproduce
tanzu apps workload create/apply -f workload.yaml --source-image gcr.io/my-playground/lsp
```
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-java-web-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tanzu-java-web-app
    apps.tanzu.vmware.com/has-tests: "true"
  annotations:
    local-source-proxy.apps.tanzu.vmware.com: my-value
spec:
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/sample-accelerators/tanzu-java-web-app
      ref:
        branch: main
```
this will result in a workload object being submitted which includes the annotation.
Update the apps plugin so the annotation is removed as expected.
